//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFFinder.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model_PDFFinder : DbContext
    {
        public Model_PDFFinder()
            : base("name=Model_PDFFinder")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group_Template> Group_Template { get; set; }
        public virtual DbSet<Report_Template> Report_Template { get; set; }
        public virtual DbSet<Statistica> Statisticas { get; set; }
    }
}
