//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PDFFinder.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report_Template
    {
        public string report_name { get; set; }
        public string printer_name { get; set; }
        public Nullable<bool> duplex { get; set; }
        public string paper_format { get; set; }
    }
}
